/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_gripper.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_gripper0.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_gripper1.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_gripper2.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_gripper3.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_gripper4.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_gripper5.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_joints0.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_joints1.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_joints2.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_joints3.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_joints4.py
/home/santiago/lab_ws/src/ur5/ur5_gazebo/scripts/send_joints5.py
import os

os.system("send_joints0.py"):	
os.system("send_joints1.py"):	
os.system("send_gripper0.py"):	
os.system("send_gripper1.py"):	
os.system("send_gripper2.py"):	
os.system("send_joints2.py"):	
os.system("send_gripper.py"):	
os.system("send_joints0.py"):	
os.system("send_joints3.py"):	
os.system("send_joints4.py"):	
os.system("send_gripper3.py"):	
os.system("send_gripper4.py"):	
os.system("send_gripper5.py"):	
os.system("send_joints5.py"):	
os.system("send_gripper0.py"):	
